# Generated by Django 5.0.3 on 2024-03-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_remove_post_link_alter_post_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="target_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
